application: helloworld
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: assets/css
- url: /js
  static_dir: assets/js
- url: /images
  static_dir: assets/images
- url: /fonts
  static_dir: assets/fonts
- url: /.*
  script: _go_app
